name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "compose.yaml" up -d --build
      
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'corretto'
        
    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build
        
    - name: Stop containers
      if: always()
      run: docker-compose -f "compose.yaml" down

    - name: Tag build
      uses: butlerlogic/action-autotag@stable
      if: success()
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"